### ISSUE TITLE
Naming conventions and contents for "Carbon GIS raw data files"

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#2]
It seems like these files (e.g. NWLAND\raw_data\gss_soc_tpha_sp9_own9_2010lt15_stats.csv) have a specific naming convention.

For this example, it seems like the filename convention is <source>_<poolCode>_<units>_????_????_YYYY????_stats.csv 

Six of the files have an "_se_" added that isn't documented. There are seven carbon pools and 13 files. Seven files have no "_se_" and six do. What are the files with "_se_"? How are they used?

**Comment by msimmond** [comment]
The "se" is likely standard errors. @aldivi can you please decode the naming convention for these files?

**Comment by aldivi** [comment]
These raw carbon files are data that have been aggregated from fine-res grids to the land categories. This aggregation was done in GRASS and was a univariate statistic calculation of the input grids within the land categories. There were two input grids: the mean cell value and the standard error (SE) of the mean cell value. The statistics were area-weighted, which means that the standard error was not mathematically propagated to the aggregated mean values, thus we tend to use the standard deviation of the mean values in space as our uncertainty metric. Comparing the average SE with the standard deviation of the mean was useful in making this decision, and some SE stats are still included in the final input files.

The naming convention is as follows:
<landfirecarbon>_<pool>_<optional input designation>_<units>_<regions>_<ownerships>_<year><land types>_<label>.csv

pools:
agc - above ground main canopy carbon
bgc - below ground main canopy carbon
ddc - dead downed carbon
dsc - dead standing carbon
ltc - litter carbon
usc - understory live carbon (assumed to be above ground for carbon dynamics)

The only optional input designation here is "se" and it represents the univariate statistics of the standard error input grid as grouped by the land categories. The average SE is included in the input files, but we don't usually use it because it is an area-weighted average instead of the propagated error associated with the mean value input grid (which is the source of the data not labelled with "se").

So this file means:
lfc_agc_se_tpha_sp9_own9_2010lt15_stats

standard error stats for above ground main canopy carbon in units of metric tonnes per hectare, grouped by 9 regions, 9 ownerships, and 15 land types, for the year 2010
