### ISSUE TITLE
CO2 or CO2e for fluxes?

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#24]
Maegen or Alan –

As in CALAND, we will have CH4 emissions to estimate for wetland soils and burning biomass, and may track BC as well. 

My (Aaron’s) understanding had been that all of the raw file data we develop for carbon densities (e.g., ‘lfc_agc_se_tpha_sp9_own9_2010lt15_stats.csv’) should be in Mg C / ha, and that all of our flux data (‘vegC_uptake’ and ‘soilC_accum’ within ‘lc_params.xlsx’) should be in Mg C / ha / yr.  

**Q1: Is this correct ?**  

I’m almost second-guessing myself now in looking at lines 224 – 252 in CALAND(), by which data frames using CO2, CH4, and BCC are converted to GWP measured in Mg CO2-eq / ha / yr:

```
# Assign CALC.GWP() (1) finds out whether each table in df.list is CO2, CH4, or BCC 
# by reading the name of the table (i.e. element name in list)
# and (2) converts gas columns to GWP accordingly

CALC.GWP <- function(df, gwp_CO2, gwp_CH4, gwp_BC) {      
  # get name of list of data frames 
  name <- names(df)
  new.df <- df
  for (l in 1:length(name)) { #loop over each data frame
    #loop over each data frame and get the unique number of columns (different for annual and cumulative)
    # loop over the C emissions columns
    for (i in 5:ncol(df[[l]])) { 
      # if not BCC and not CH4C
      if ((substr(name[[l]], nchar(name[[l]])-2, nchar(name[[l]]))) != "BCC" & 
          (substr(name[[l]], nchar(name[[l]])-2, nchar(name[[l]]))) != "H4C") {
        # then it's CO2C, so covert C to CO2 according to molar mass ratio 
        new.df[[l]][,i] <- df[[l]][,i] * (44.01/12.0107) * gwp_CO2 
        # otherwise if it's CH4C
      } else { if (substr(name[[l]], nchar(name[[l]])-2, nchar(name[[l]])) == "H4C") {
        # convert CH4-C to [Mg CO2-eq/ha/y]
        new.df[[l]][,i] <- df[[l]][,i] * (16.04/12.0107) * gwp_CH4
        # otherwise it's BCC, so convert to [Mg CO2-eq/ha/y]
        # multiplying by 1/0.6 based on assumption that 60% black C is C.
      } else { new.df[[l]][,i] <- df[[l]][,i] * (1/0.6) * gwp_BC } 
      }
    }
  }
  return(new.df)
}
```

**Q2.1: From which raw data tables are these data frames taken ?** 

**Q2.2.Are there any raw data we should calculate in CO2, CO2-eq, CH4, or BC (i.e., by ha, or by ha and yr), rather than C ?**

**Comment by msimmond** [comment]
Hi Steve, I'm tagging Alan @aldivi per our conversation last meeting to keep us both in the loop on development questions. Q1: Yes, all the raw inputs in lc_params are in Mg C/ha or Mg C/ha/y. Note that the raw scenario input file can be in acres. Q2.1. CALC.GWP() converts the species-specific carbon fluxes (CO2-C, CH4-C, and optional Black carbon-C) simulated in the annual loops of CALAND() into CO2-equivalents. The fluxes are stored in dataframes while CALAND() is running which are the arguments used when CALC.GWP() is called within CALAND(). The purpose of CALAC.GWP is so that CALAND() outputs both the carbon units of each species (CO2-C, CH4-C, and black-C) (Mg C / ha / y) as well as their CO2-equivalents (Mg CO2e /ha / y). The CO2e are calculated in CALC.GWP using the global warming potentials (gwp_CO2, gwp_CH4, gwp_BC) that are assigned within CALAND().  Q2.2. I don't think so. However you may want to revisit the fractions that are assigned to partitioning carbon fluxes into CO2-C, CH4-C, and Black-C. The fractions (or partitioning coefficients) are assigned within CALAND() prior to the annual loop (e.g., marsh_CO2_C_frac, marsh_CH4_C_frac, CO2C_fire_frac).

**Comment by aj1s** [comment]
This is very helpful – thanks Maegen.  (Also, thanks for the reminder that it’s fine to simultaneously tag Alan on these questions.)  Here I’m also tagging Teresa (@tchapman100) so she’s aware you’ve fielded this shared question of ours.

re Q2.1: I see; so these data frames are generated within CALAND() and not created through direct import of raw data I was concerned we were missing.
