### ISSUE TITLE
How is the reforestation pathway implemented?

### ISSUE THREAD

**Issue by sbassett** [TNC-NMFO/NWLAND#4]
As a pathway to study as an example, this one seems like a good balance between simple and complex. The shrubToForest conversion seems interesting, and the calculation of treatable area using a distance from edge of burn metric seems interesting.

**Comment by msimmond** [comment]
I think there are 2 ways to implement it. If you want to implement 100% reforestation of non-regenerating forest due to high severity wildfire, you can run the baseline with the NR setting turned on (e.g., NR=120) and the alternative scenario with NR turned off (i.e., full regeneration). That's how we simulated the CA land use policy scenarios. Alternatively, you can explicitly prescribe reforestation areas as a practice in the scenario input file and it will be treated as a restoration practice, converting shrubland to forest. Note that this practice is prioritized in terms of shrubland area availability per region-ownership over afforestation and meadow restoration, which can also come from shrubland among others.

**Comment by msimmond** [comment]
@aldivi are there any other caveats?

**Comment by aldivi** [comment]
Reforestation is a land cover change, and so is implemented in this part of the code. It converts only shrubland to forest, while afforestation converts both grassland and shrubland to forest. The difference between these two could be interesting, depending on how your grassland is parameterized. In CA, our grassland has annual carbon loss, so afforestation has a much more dramatic response than reforestation, and so we are wary of using afforestation as it may cause some overestimation of benefits. Reforestation is designed to complement non-regeneration, which converts forest to shrubland.
