### ISSUE TITLE
CALAND() cannot find test carbon input file due to unnecessary subdir

### ISSUE THREAD

**Issue by aj1s** [TNC-NMFO/NWLAND#61]
Sourcing  'write_calands_inputs.r' anew with '2021_05_19_testingWriteInputsWithPlaceholderData_noHere.r' returned error:

`Error: FileNotFoundException (Java): File '2021_05_14_carbon_input_nwland_testAN.xls' could not be found - you may specify to automatically create the file if not existing.`

**Comment by aj1s** [comment]
Modifying lines 210 and 211 in CALAND() 
```
# this enables java to use up to 4GB of memory for reading and writing excel files
options(java.parameters = "-Xmx4g" 

```
may be necessary to provide more memory to Java (or, possibly XLConnect and rJava, specifically, as in Issues #7 and #8).

**Comment by sbassett** [comment]
I received this same error because the  CALAND() `indir` argument is concatenated with "inputs/" on line 277 and i was passing it the file name and the full path so it was looking in "inputs/./inputs/2021_05_14_carbon_input_nwland_testB1". Calling CALAND() with `indir = "2021_05_14_carbon_input_nwland_testB1"` works for me.
